### ISSUE TITLE
bug: "No such file or directory" when running scripts in self hosted Kubernetes

### ISSUE THREAD

**Issue by BojanOro** [windmill-labs/windmill#1005]
### Describe the bug

I have just set up Windmill self-hosted in Kubernetes. When attempting to run any script, in any language, I am given the following:

```
The result keys are: error
error before termination: IoErr(
    Os {
        code: 2,
        kind: NotFound,
        message: "No such file or directory",
    },
)
```

### To reproduce

1. Install Windmill self-hosted in Kubernetes
2. Attempt to load any sample script
3. Click Test

### Expected behavior

I expect the script to execute without error.

### Screenshots

<img width="1980" alt="image" src="https://user-images.githubusercontent.com/9300518/206519726-6895cef0-abd6-4c9e-a930-b183982442d7.png">

### Application version

Windmill v1.53.0-20-g08bfc102

### Additional Context

I should note that I could not follow the database set up instructions perfectly as I do not have superuser access to the database (using Azure managed postgres). I was able to get a similar set up by creating the `windmill` database with owner `windmill_admin` which lets me avoid adding the `WITH BYPASSRLS;` since I cannot execute that without superuser access.

**Comment by rubenfiszel** [comment]
Hello,

To run Windmill without superadmin access to the DB, one can follow this section: https://docs.windmill.dev/docs/how-tos/self_host#run-windmill-without-using-a-postgres-superuser, curious to know if that is applicable to your case.

I think it's failing in every language because you are using windmill non-ee that doesn't include by default nsjail, and that you have overriden DISABLE_NSJAIL to be false. Could you list the environment variables that you are using and curious to know what templates you used.

**Comment by BojanOro** [comment]
I have read that document, however in my case I simply don't have a superuser account on the database, _at all_. That said, I've run the parts of that document that I can, and got around the `CREATE ROLE windmill_admin WITH BYPASSRLS;` line by making `windmill_admin` owner of the database which seems to have worked.

It does seem like the issue was related to nsjail - I assumed that the Helm chart would use defaults if not specified in the `values.yaml` file, but I guess it requires all the values present. Seems to work now, appreciate the quick response!
