### ISSUE TITLE
feature: accept unauthenticated webhooks

### ISSUE THREAD

**Issue by singletonerik** [windmill-labs/windmill#1723]
Right now one can only trigger a script/flow using webhooks with token authentication in the request header. Many cloud systems offering custom webhooks, but I haven't seen any that allow a user to add custom headers (I could give dozens of examples) - most are unauthenticated POST requests. Is there a way to trigger a script/flow without an auth header? If not, could you please add this capability?

**Comment by rubenfiszel** [comment]
The token can be passed as query arg:
`<webhook>?token=XXXX` (https://docs.windmill.dev/docs/core_concepts/webhooks#triggering)

and the token can be made specific to the webhook: (https://docs.windmill.dev/docs/core_concepts/webhooks#webhook-specific-tokens). 

Sharing a public url with the token in query arg with a webhook specific token is equivalent to not requiring auth since the webhook will work "on behalf of'. Tokens are required to know what permission the script/flow has and what resources/variables and other scripts it can trigger.

**Comment by singletonerik** [comment]
Ok thank you that should work. One more question about webhooks.

if I have a script like so:
```python
def main(x:str):
    print(x)
    return x
```
It appears that the script will only run if the body is {"x":"abc"} (and sets x="abc") but it will fail on {"y":"abc"}. Is there a way to write `main` to accept any string or json.

**Comment by rubenfiszel** [comment]
```
def main(**kwargs)
    ....
```
