### ISSUE TITLE
feature: MQTT Trigger

### ISSUE THREAD

**Issue by TheOneValen** [windmill-labs/windmill#1966]
It would be great to have other triggers than webhook. I propose a MQTT trigger which is configured for a specific topic. Alternatively the topics are set by windmill as with urls for webhooks.

**Comment by rubenfiszel** [comment]
My answer will be similar than for nats.io (see: https://github.com/windmill-labs/windmill/discussions/1577)

I think it's much better that one use a bridge/sidecar container that push to windmill rather than windmill support it natively. We call those adapters, and we have built one for postgres triggers at: https://github.com/windmill-labs/windmill-adapters. This adapter would be run alongside windmill, act as a mqtt sink and send http payloads according to your own rules. If you were to build a generic one, we would be happy to include it in the windmill-adapters repo.

**Comment by TheOneValen** [comment]
@rubenfiszel can this be reopened? It seems that windmill evolved to support other trigger types.

**Comment by AndreHaase** [comment]
> My answer will be similar than for nats.io (see: [#1577](https://github.com/windmill-labs/windmill/discussions/1577))
> 
> I think it's much better that one use a bridge/sidecar container that push to windmill rather than windmill support it natively. We call those adapters, and we have built one for postgres triggers at: https://github.com/windmill-labs/windmill-adapters. This adapter would be run alongside windmill, act as a mqtt sink and send http payloads according to your own rules. If you were to build a generic one, we would be happy to include it in the windmill-adapters repo.

@rubenfiszel nats seems to be supported now (ee only?) is there any chance mqtt will be supported for ce? Would be a cool tool in the homeautomation space then...

**Comment by lublak** [comment]
@rubenfiszel It would also be nice to have direct support for MQTTS. So MQTT with TLS, when MQTT comes :)
