### ISSUE TITLE
race condition issue of concurrency limit when N workers are fetching jobs at the same time

### ISSUE THREAD

**Issue by fatonramadani** [windmill-labs/windmill#2216]
[MESSAGE_ID=1147097085464817684]

**Comment by rubenfiszel** [comment]
See https://github.com/windmill-labs/windmill/issues/1903#issuecomment-1702421353

The reason is pretty simple, the concurrency limit is checking for the number of jobs currently in the queue, but all the workers are doing the transaction concurrently so they do not see the other jobs as running.

2 solutions:
1. Do a concurrency limit check later as well (bad)
2. Use atomic locks per script_path that are increased/decreased with a row lock (good)

**Comment by rubenfiszel** [comment]
We went for solution 2
