### ISSUE TITLE
feature: Can make some parts of flow to be synchronous and some part asynchronous

### ISSUE THREAD

**Issue by rafelpermata** [windmill-labs/windmill#2698]
Hi, I just tried windmill, and I love it. 

I would like to the possibility of the feature in the title. Can windmill already do this? I cannot find this feature in the documentation.

I'd like to make the flow sync on some parts and the rest is async. 

Example use case:
- sync for input validation through db etc
- need to make sure the client know the first script is done and thr client doesnt care about the rest

Is this feasible?

**Comment by rubenfiszel** [comment]
We have on our todo to make the sync behavior configurable. You would be able to define a step at which the sync endpoint would return (and it would return that step's result) instead of waiting for the full flow result.

It's unclear to us if we would gate this under EE at this time. Expect to have an early version of this before end of next week.

**Comment by rubenfiszel** [comment]
It is now implemented and open-source
![image](https://github.com/windmill-labs/windmill/assets/275584/ad875505-9409-40eb-8f7e-d74e890b55f4)

The flow will stop the sync endpoint at the node defined there and continue the flow asynchronously
