### ISSUE TITLE
bug: oauth.json not working anymore

### ISSUE THREAD

**Issue by legalgig** [windmill-labs/windmill#2877]
### Describe the bug

Hi,

I was using windmill with zitadel as IDP but sadly the button to use oidc has disappeared after an update from v1.224.0 to v1.227.1. I tried to downgrade windmill to an older version but it didn't help.

### To reproduce

1. Create oauth.json file with this content
```
{
  "zitadel": {
    "id": "client_id",
    "secret": "client_secret",
    "login_config": {
      "auth_url": "https://zitadelUrl/oauth/v2/authorize",
      "token_url": "https://zitadelUrl/oauth/v2/token",
      "userinfo_url": "https://zitadelUrl/oidc/v1/userinfo",
      "scopes": [
        "openid",
        "profile",
        "email"
      ]
    }
  }
}
```
2. mount file into `/usr/src/app/oauth.json`
3. Windmill UI will show only email and password fields 

### Expected behavior

oauth.json file should configure sso

**Comment by rubenfiszel** [comment]
Hi @legalgig ,

I don't recall us doing any change to explicitly disable oauth.json but we are not actively maintainig it anymore because it has been deprecated in favor of doing everything in the UI. 

You can do a PR and add it as one of the officially supported IDP following this example PR: https://github.com/windmill-labs/windmill/pull/2871 or alternatively pro/ee allow you to set custom sso/oauth directly in the UI.

**Comment by legalgig** [comment]
Thanks! I've opened a PR with Zitadel OIDC configuration
