### ISSUE TITLE
Clarify Licensing in Documentation

### ISSUE THREAD

**Issue by razuro** [windmill-labs/windmill#4514]
I love Windmill, I think the implementation is the best among all, hands down, that covers most use cases. 

Initially when reading the usage license in the [documentation](https://www.windmill.dev/terms) there is no mention of AGPLv3, it is not clear to me that this is dual license as AGPLv3 for the OSS version and different licensing for the Enterprise, until I was too deep and checked the code, then I discovered the actual license in Github.

Most people are not aware of the AGPLv3 license (organisation avoid using anything licensed as AGPLv3), hence why not just mention upfront that this is dual license. IMHO, would you consider to license this as ELv2 instead of AGPLv3 like Airbyte?

**Comment by rubenfiszel** [comment]
We're pretty upfront in the Readme of the github project that it's AGPLv3 with a commercial license for enterprise. Also AGPLv3 fits better our needs than ELv2. 

We're fine with some organization having issues with the AGPLv3, they can upgrade to the Enterprise Edition to avoid any legal headaches but there are really no ambiguity that it's completely fine for an organization to use the stock version of Windmill internally as they please, AGPLv3 doesn't cover the code they run on Windmill.

We are COSS, we're happy with code contributions and forks as long as they stay open-source/AGPLv3.

Pretty much all questions around licensing come from users trying to white-label us or trying to build a business around selling Windmill and being competitive with us in some ways . That's not covered by the AGPLv3. We currently have many customers white-labeling us and you'd need the Commercial License to do this.

**Comment by razuro** [comment]
For our case, we didn't use it because we want to white label it. Let's agree to disagree, and I really appreciate how you were always to respond to most issue here. Thanks for creating Windmill, if there's a change to the license in the future, I'll not hesitate to come back and support. Cheers! 🙌

**Comment by pReya** [comment]
> Pretty much all questions around licensing come from users trying to white-label us or trying to build a business around selling Windmill and being competitive with us in some ways . That's not covered by the AGPLv3. 

Would you mind explaining how exactly whitelabelling is not covered under AGPLv3? In my naive understanding, I can modify it as much or little as I want (e.g. add my own designs and logos) and sell the resulting product, as long as I publish the source code of my result under the same license.

**Comment by rubenfiszel** [comment]
It's not in our best interest to describe exactly how to go around the things that we deem unethical (slapping your name and logo on software you didn't make and calling it a day) and competitive with us resulting in removing a source of income for that same very project.
- Your users need to be made clearly aware of how to get the sources and that it is a fork of Windmill. Slapping your brand and logo goes against that spirit.
- Any modification of the software, including embedding it in your product is a modification of the software that will force you to also release the embedding layer with the same AGPLv3 license
- We will use all the legal means at our disposal if you are building a business trying to profiteer from our hard work, and we deem whitelabelling to be such a case

I'm a software engineer, not a lawyer and I'm not super interested to talk about the specifics of AGPLv3. There are technical ways to make this even more impractical than it already is by having more of the code that would enable to easily have a multi-tenant architecture be gated under our private fork of Windmill for the EE. We would rather spend our time on building features for everyone and improve the software but the more we will see people trying to use our own work against us, the more we will prioritize it.

**Comment by ssddanbrown** [comment]
Hi @rubenfiszel,
Sorry to query this further, since you're not interested to talk about specifics of the AGPLv3, but I think it's probably best to understand potential licensing problems early rather than have them pop up later. Also, I'm no legal expert, just someone that's spent some fair time looking over the AGPLv3 and its uses.

---

> Slapping your brand and logo goes against that spirit.

Against the spirit of the project maybe, but not of the license. The forking of projects to new ownership and branding is a core element of free/open source software, and the AGPLv3 does not protect against this.

> Any modification of the software, including embedding it in your product is a modification of the software that will force you to also release the embedding layer with the same AGPLv3 license

If "embedding" in this context is via network means (iframe/API) then that would not typically trigger copyleft requirements of the AGPLv3. This is a common misconception. The network part of the license applies to what's considered distribution and when sources/license terms have to be provided. So in this context, where end-users can see embedded parts of the (Windmill, not embedding) app, they'd just need means of requesting sources/terms to that part.

> We will use all the legal means at our disposal if you are building a business trying to profiteer from our hard work, and we deem whitelabelling without a commerical license to be such a case

Okay, but the AGPLv3 does not specifically protect you or give you legal basis in that regard. Preventing means of modification then may go against the license.

---

Looking further at the license setup of the project, it's quite complex with the within-file mix of licensing, which the AGPLv3 does not play well with. I'd say there's a significant case to be made that you could follow [section 7](https://github.com/windmill-labs/windmill/blob/b0fffe11ebfbf01bec255af80b648714b031d1bd/LICENSE-AGPL#L376-L380) to just remove all added terms of the "enterprise" flagged code:

_"All other non-permissive additional terms are considered "further restrictions" within the meaning of section 10. If the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term."_

---

> Pretty much all questions around licensing come from users trying to white-label us or trying to build a business around selling Windmill and being competitive with us in some ways . That's not covered by the AGPLv3. 

The AGPLv3 does not prevent that, and in fact it specifically allows it, as long as the same rights/terms are provided to their users too.

If you're against people (including commercial entities) benefiting/profit/competing from your work, then you may be in contention with not just the AGPLv3, but open source & free software in general, as their common definitions provide those rights. If you need defences against competing use, you may want to seek alternative means of licensing and distribution.
