### ISSUE TITLE
Browser automation failing

### ISSUE THREAD

**Issue by hershagarwal** [windmill-labs/windmill#4801]
All of my scripts that use puppeteer have suddenly started failing as of Monday. Upon trying windmill’s sample browser automation code, it looks like even that isn’t working, leading us to believe it’s not an issue with our code.

This is the error message: {
    "error": {
        "name": "Error",
        "stack": "page: Target page, context or browser has been closed\n    at <anonymous> (/tmp/bun/main.ts:10:30)\n    at processTicksAndRejections (/tmp/bun/native:7:39)",
        "message": "page: Target page, context or browser has been closed",
        "step_id": "b"
    }
}

**Comment by HugoCasa** [comment]
We've updated the docs, you need to pass some additional arguments to puppeteer/playwright: https://www.windmill.dev/docs/advanced/browser_automation#examples

**Comment by hershagarwal** [comment]
Got it, thank you.

Do you know why this broke all of my workflows that relied on this code?
Did Windmill make changes to the module?

If so, how can I prevent this from happening in the future. This is the
second time we've had our workflows break due to changes, so I'm worried
about relying too much on Windmill in the future if I can't find a way to
maintain stability.

**Comment by HugoCasa** [comment]
The issue is probably related to a change in Chromium, not something Windmill directly changed. That said, I agree it’s annoying when workflows break unexpectedly.

One way to avoid this in the future is to pin the Chromium version in the init script of the Chromium worker group (https://www.windmill.dev/docs/advanced/preinstall_binaries#init-scripts). We'll probably update the default init script for chromium too.

**Comment by hershagarwal** [comment]
Ok thank you. We're on the cloud version, so that would be great if the
default init script was updated since it looks like the editing is only
possible in self-hosted and enterprise.
