### ISSUE TITLE
bug:Getting error while connecting to external  database

### ISSUE THREAD

**Issue by Somraj-Seal** [windmill-labs/windmill#4843]
### Describe the bug

Getting this error while connecting to external  database
`
Error: Connecting to database: error returned from database: no pg_hba.conf entry for host "XXX", user "XXX", database "XXX", no encryption
`

### To reproduce

Try connecting with an external database

### Expected behavior

Successful connection

**Comment by rubenfiszel** [comment]
not a windmill issue but issue with credentials used or credentials allowed on db  (which may be ssl dependent)

**Comment by hkader-tl** [comment]
@rubenfiszel seems like you run into this if you are spinning things up with the tf files here: https://github.com/windmill-labs/windmill/tree/main/examples/deploy/aws-ecs-terraform

seems like on recent RDS versions the default setting is `force_ssl` to be true which is in conflict with the postgres connection string that is being used in the TF repo (https://github.com/windmill-labs/windmill/blob/main/examples/deploy/aws-ecs-terraform/windmill_worker_basic.tf#L29)

happy to submit a PR if my fix (to remove the `sslmode=disable` from the connection string) is the right one. seems to fix things since I believe in a prior PR you guys added support for windmill to verify.

**Comment by rubenfiszel** [comment]
Yes please, a PR would be fantastic
