### ISSUE TITLE
[Minor] [UX] Break down script kind help text

### ISSUE THREAD

**Issue by malomarrec** [windmill-labs/windmill#784]
#### Problem
The help text on script kinds is way too big and illegible.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/25070988/197031081-c8b15672-1020-40e0-b04b-63e7439e2452.png">

#### Fix

Consider moving to smaller help texts for each script kind instead
<img width="662" alt="Screen Shot 2022-10-20 at 8 41 14 PM" src="https://user-images.githubusercontent.com/25070988/197031561-66f5a9a2-c20d-4471-8dda-fe78be8f1e22.png">

**Comment by rubenfiszel** [comment]
Fixed by making it more discreet (hidden by default unless clicking on button) and moving tooltip to each script kind
![Screenshot 2022-10-21 at 14-25-45 New Script Windmill](https://user-images.githubusercontent.com/275584/197195364-e95b5caf-5da6-4dc7-be7c-6e1dcb30cafe.png)
![Screenshot 2022-10-21 at 14-25-39 New Script Windmill](https://user-images.githubusercontent.com/275584/197195369-3160b147-d155-4040-9c41-f3ea0ed54c07.png)
